### ISSUE TITLE
Do not show any message if plugins are up-to-date 

### ISSUE THREAD

**Issue by kopach** [semanser/vim-outdated-plugins#11]
Currently, if all plugins are up to date - the plugin will show "All plugins up-to-date" message on vim startup. There is big disadvantage in such approach - if any other plugin will have any errors - current plugin will override that message. E.g. recently I had a problem with one plugin, which was posting it's error in the same line as vim-outdated and it was almost impossible to note this error.

Also, personally I don't care much if all my plugins are up to date. I would like to be informed only if plugins are outdated - so I can decide what to do with that.

**Comment by semanser** [comment]
Hi @kopach. You can run `:messages` command to see all the previous messages in vim or neovim.

**Comment by kopach** [comment]
Thanks @semanser, good to know. Anyway, this doesn't solve my problem. My "broken plugin" was sending me an error message on vim startup, but I just haven't time to see it because `vim-outdated` was overriding it for me very rapidly. So, it was just like almost not noticeable blinking. And only after noticing this "blinking" error I understood why I had troubles in vim for few days already and could fix that.

So, personally I would suggest disabling `"All plugins up-to-date"` message at all or at least add configuration option to do so.

**Comment by semanser** [comment]
Hey, thanks for your suggestion about the variable. Now you can use a variable to configure this behavior.
```
let g:outdated_plugins_silent_mode = 1
``` 

Done in 
https://github.com/semanser/vim-outdated-plugins/commit/5d2046862962203b6e73b2c3186e5a1736ab873b
