### ISSUE TITLE
Normalize async job for Vim and Neovim

### ISSUE THREAD

**Issue by semanser** [semanser/vim-outdated-plugins#9]
Probably use https://github.com/prabirshrestha/async.vim plugin.

**Comment by kopach** [comment]
Hi. This plugin is awesome. Thank you man. The only issue with it for me is that it slows down (just a little bit) my vim during startup. So, it would be really cool to fix that somehow. Do you have any plans on this issue?

**Comment by semanser** [comment]
Hi @kopach. Thank you for your feedback. This issue is not related to performance problems.

I will be appreciated if you create a new issue and describe your problem there. Thanks!

**Comment by kopach** [comment]
Done. Created separate issue #10
